#!/bin/bash

### set the job name
#PBS -N sci-drop-atac-100k
#PBS -l select=1:ncpus=21:mem=126gb:pcmem=6gb
#PBS -l place=pack:shared
#PBS -l pvmem=168gb

# Maximum CPU and clock time per job
#PBS -l cput=50:00:0

### Wall time is the total length of realtime that a script will be on the cluster before being stoped
#PBS -l walltime=10:00:0

# Submit an array of jobs to run the script multiple times
###PBS -J 1-100

# Which queue should we use?
# The queue determines how quickly nodes required to run a job
# High and standard priority use group time
# Windfall uses no time, but is the lowest priority for getting nodes
###PBS -q oc_high_pri
#PBS -q oc_standard
###PBS -q oc_windfall


# Ensure your time gets charged to the group
#PBS -W group_list=cusanovichlab
# Pass your environment variables to the pbs job
#PBS -V
# Join standard out and standard error messages
#PBS -j oe
echo 'running'

### run your excutable program with begin and end date and time output
date
# use unsplitting line flag next time
OUTDIR=/xdisk/darrenc/mig2020/rsgrps/cusanovichlab/projects/sciATAC_projects/20200716_sci_drop_atac_100k
mkdir $OUTDIR/fastqs
bcl_dir=/xdisk/darrenc/mig2020/rsgrps/cusanovichlab/projects/sciPLEX_projects/200715_firstsciplex/200715_NB501893_0155_AHCLL5AFX2

# the library was mixed with sci-plex, so use use-bases-mask to extract the cycles for sci-drop-atac
# refer https://www.biostars.org/p/344768/
bcl2fastq --runfolder-dir $bcl_dir \
               -o $OUTDIR/fastqs \
               --sample-sheet $OUTDIR/SampleSheet.csv \
               --ignore-missing-bcls \
			   --no-lane-splitting \
			   --use-bases-mask Y*,I8N*,I*,Y77N*
#bcl2fastq --runfolder-dir /rsgrps/cusanovichlab/projects/bulk_atac/various_060719/sequencing/190607_NB501893_0106_AHJ2CYAFXY/ \
#               -o /rsgrps/cusanovichlab/projects/bulk_atac/various_060719/fastq/ \
#               --interop-dir /rsgrps/cusanovichlab/projects/bulk_atac/various_060719/interop/ \
#               -r 6 -w 3 \
#               --sample-sheet /rsgrps/cusanovichlab/projects/bulk_atac/various_060719/SampleSheet.csv \
#               --create-fastq-for-index-reads \
#			   --ignore-missing-positions \
#               --ignore-missing-controls \
#               --ignore-missing-filter \
#               --ignore-missing-bcls \
#			   --no-lane-splitting
date
